Downgrade matplotlib
Our code still uses a function that was removed, so we get the following
error if we try to use 3.9.0

AttributeError: module 'matplotlib.cm' has no attribute 'get_cmap'